enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Reddit-Extended]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
patches-version = "pre-release"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = ""
version = "auto"

[YouTube]
app-name = "YouTube"
enabled = true
#patches-source = "ReVanced/revanced-patches"
patches-version = "pre-release"
#integrations-source = "ReVanced/revanced-integrations"
#cli-source = "j-hc/revanced-cli"
#rv-brand = "ReVanced"
build-mode = "both"
excluded-patches = "'Theme'"
included-patches = "'MaterialYou'"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"                                  
version = "auto"

[YouTube-Extended]
app-name = "YouTube RVX"
enabled = true
patches-source = "inotia00/revanced-patches"
patches-version = "pre-release"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Theme'"
included-patches = "'MaterialYou''Change header'"
patcher-args = "-Oheader=UToob"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
version = "auto"
